#!/bin/sh
cd /mnt/sdcard/hacks/onvif-server/bin

source /mnt/data/etc/os-release

STEPS=5
MOTOR_CONTROL="/mnt/sdcard/hacks/motor-control/bin"
EVENT_FILE="$MOTOR_CONTROL/event"

LEFT="echo pan forward $STEPS > $EVENT_FILE"
RIGHT="echo pan reverse $STEPS > $EVENT_FILE"
UP="echo tilt forward $STEPS > $EVENT_FILE"
DOWN="echo tilt reverse $STEPS > $EVENT_FILE"


IP_ADDR=$(ip -4 addr show wlan0 | grep inet | awk '{print $2}' | cut -d'/' -f1)
while [[ -z $IP_ADDR ]]; do
    IP_ADDR=$(ip -4 addr show wlan0 | grep inet | awk '{print $2}' | cut -d'/' -f1)
done
echo $IP_ADDR

ONVIF_PROFILE_0="--name HD --width 1920 --height 1080 --url rtsp://$IP_ADDR:8554/mainstream --type H264"
ONVID_PROFILE_1="--name SD --width 640 --height 360 --url rtsp://$IP_ADDR:8554/substream --type H264"
echo $ONVIF_PROFILE_0
echo $ONVIF_PROFILE_1

exec ./onvif_srvd --no_fork --pid_file /var/run/onvif_srvd.pid --model "MJSXJ05CM" --manufacturer "Xiaomi" --ifs wlan0 --port 5000 --scope onvif://www.onvif.org/Profile/S $ONVIF_PROFILE_0 $ONVIF_PROFILE_1 \
        --ptz \
        --move_left "eval $LEFT" \
        --move_right "eval $RIGHT" \
        --move_up "eval $UP" \
        --move_down "eval $DOWN"