name: CI

on:
  push:
    branches:
      - '*'

env:
  sourceBranch: ${{ github.ref }}
  isNightly: ${{ contains(github.ref, 'dev') }}
  isFinalRelease: ${{ contains(github.ref, 'master') }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    # - name: Build
    #   uses: dawidd6/action-ansible-playbook@v2
    #   with:
    #     playbook: build.yml
    #     directory: ./
    #     options: |
    #       --extra-vars branch=${{ github.ref }}

    - name: Build latest
      if: ${{ env.isNightly == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build dev

    - name: Build stable
      if: ${{ env.isFinalRelease == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build final

    - name: Release latest
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isNightly == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/sdcard.zip
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: latest-rc

    - name: Release stable
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isFinalRelease == 'true'
      with:
        automatic_release_tag: stable
        files: dist/sdcard.zip
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: stable
